---
antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Introduction"
    - name: module-01
      label: "Module 1: Inspect a Classical SSH Session"
    - name: module-02
      label: "Module 2: Enforce Hybrid Post-Quantum Key Exchange (ML-KEM)"
    - name: module-03
      label: "Module 3: Create and Use Post-Quantum Authentication Keys (ML-DSA)"

tabs:
  - name: ">_ Client"
    path: /wetty
    port: 443
  - name: ">_ Server"
    path: /terminal2
    port: 443
  - name: Crypto Policies Docs
    url: 'https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening'
